### ISSUE TITLE
Ramsay Issue

### ISSUE THREAD

**Issue by MelonicOverlord** [MFHKiwi/super-smash-aeugh#4]
When going in a straight line for a long time, Ramsay starts to have a heart attack (basically).

[Bug Demonstration Video Link](https://www.youtube.com/watch?v=hsPFIAdWFK4&feature=youtu.be)

**Comment by MFHKiwi** [comment]
I already knew of this bug and know why it's occurring; I just haven't figured out how to patch it yet. Thank you for your report.
