### ISSUE TITLE
Screen Edges

### ISSUE THREAD

**Issue by MelonicOverlord** [MFHKiwi/super-smash-aeugh#6]
On my (I think) 15 inch laptop screen, I'm able to go off of the right and bottom of my screen, presumably because it's too small for the game which means when carrots spawn out there it's hard to get them.

**Comment by Lukas-Batema** [comment]
> On my (I think) 15 inch laptop screen, I'm able to go off of the right and bottom of my screen, presumably because it's too small for the game which means when carrots spawn out there it's hard to get them.

f

**Comment by MFHKiwi** [comment]
The game creates a 1024x768 window by default. If you somehow own a computer with a screen resolution smaller than that, you can edit `RenderWindow window(VideoMode(1024, 768), "Super Smash AEUGH");` in `main.cpp`.

**Comment by MelonicOverlord** [comment]
Maybe I should **_not_** fullscreen then?

**Comment by MFHKiwi** [comment]
> Maybe I should **_not_** fullscreen then?

That's your issue. The screen does not automatically resize. I don't currently know whether it's possible to implement that, but such things will come much later.

**Comment by MelonicOverlord** [comment]
Righty

**Comment by MFHKiwi** [comment]
This bug has been fixed in commit 3b493e497fe2f4df86a95264b97c1fe080f85f4b.
